name: Snyk Security

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master"]
jobs:
  gitleaks:
    name: 🐛 Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.13.0/gitleaks_8.13.0_linux_x64.tar.gz
          tar -xzf gitleaks_8.13.0_linux_x64.tar.gz
          sudo install gitleaks /usr/bin

      - name: Run Gitleaks and generate SARIF
        run: |
          gitleaks detect --report-format sarif --report-path gitleaks.report
        continue-on-error: true

      - name: Echo report
        run: cat gitleaks.report

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v5
        with:
          sarif_file: gitleaks.report
